language: php

sudo: false

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    allow_failures:
      - php: nightly
    include:
        - php: 5.5
          services:
            - docker
        - php: 5.6
          services:
            - docker
        - php: 7.0
          env: deps=low
          services:
            - docker
        - php: 7.1
          env: deps=high
          services:
            - docker
        - php: nightly
          env: deps=high
          services:
            - docker

before_install:
    - stty cols 120
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - if [[ $deps = high ]]; then composer update --no-interaction --no-progress --ansi; fi
    - if [[ $deps = low ]]; then composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable; fi
    - if [[ ! $deps ]]; then composer install --no-interaction --no-progress --ansi; fi
    - ./tests/setup.sh

script:
  - mkdir -p build/logs
  - ./tests/run.sh --coverage-clover build/logs/clover.xml

notifications:
    email: false

after_success:
  - travis_retry wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - travis_retry php coveralls.phar -v

